ALTER TABLE rate_plans
ADD COLUMN IF NOT EXISTS start_date DATE,
ADD COLUMN IF NOT EXISTS end_date DATE,
ADD COLUMN IF NOT EXISTS days_of_week JSONB,
ADD COLUMN IF NOT EXISTS priority INTEGER DEFAULT 0;
